"""
Upload rendered GTA VI brainrot shorts to Instagram Reels.
Uses instagrapi (unofficial but free) for posting.
Relies on a pre-generated session file from setup_instagram.py
since Instagram blocks direct logins from cloud servers.
"""
from __future__ import annotations

import sys
from pathlib import Path

import config

IG_TIMEOUT = 60


def upload_reel(
    video_path: Path,
    caption: str = "",
) -> str:
    """
    Upload a short to Instagram Reels using instagrapi.
    Requires a session file generated by setup_instagram.py.
    """
    if not video_path.exists():
        print(f"❌ Video not found: {video_path}")
        return ""

    if not config.IG_USERNAME or not config.IG_PASSWORD:
        print("⚠ IG_USERNAME / IG_PASSWORD not set — skipping Instagram upload")
        return ""

    print(f"📱 Instagram: uploading as {config.IG_USERNAME}…")

    try:
        from instagrapi import Client
        from instagrapi.exceptions import ClientError

        settings_path = config.CACHE_DIR / "ig_settings.json"
        settings_path.parent.mkdir(parents=True, exist_ok=True)

        if not settings_path.exists():
            print("⚠ No saved Instagram session found.")
            print("   Instagram blocks logins from cloud servers (CSRF error).")
            print("   Run 'python setup_instagram.py' on your LOCAL PC to generate a session,")
            print("   then commit and push the session file.")
            print("   Skipping Instagram upload.")
            return ""

        cl = Client()
        cl.load_settings(str(settings_path))
        import socket
        socket.setdefaulttimeout(IG_TIMEOUT)
        cl.delay_range = [1, 3]

        # Verify session is still valid
        try:
            cl.get_timeline_feed()
            print("   ✅ Session valid")
        except Exception:
            print("⚠ Saved Instagram session has expired.")
            print("   Run 'python setup_instagram.py' on your LOCAL PC to refresh it,")
            print("   then commit and push the updated session file.")
            print("   Skipping Instagram upload.")
            return ""

        # Build caption with hashtags
        hashtags = (
            "#GTAVI #GTA6 #GamingShorts #Brainrot #GTA6Gameplay "
            "#GamingMemes #Reels #GTA6Moment #RockstarGames"
        )
        full_caption = f"{caption}\n.\n{hashtags}" if caption else hashtags

        print("   📤 Uploading Reel…")
        result = cl.clip_upload(str(video_path), full_caption)
        media_id = result.id
        print(f"   ✅ Uploaded! Media ID: {media_id}")
        return str(media_id)

    except ImportError:
        print("⚠ instagrapi not installed. Install with: pip install instagrapi")
        return ""
    except Exception as e:
        print(f"❌ Instagram upload failed: {e}")
        return ""


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--video", required=True, help="Path to MP4")
    ap.add_argument("--caption", default="GTA VI BRAINROT 🎮🔥", help="Reel caption")
    args = ap.parse_args()

    upload_reel(Path(args.video), args.caption)